# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-31 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czat', '0003_auto_20200130_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nieobecnosc',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Nieobecnosc',
        ),
    ]
