# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-31 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('czat', '0004_auto_20200131_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nieobecnosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=100, verbose_name='powod nieobecnosci')),
                ('data_pub', models.DateTimeField(verbose_name='data zgłoszenia')),
                ('data_start', models.DateField(verbose_name='data pierwszego dnia nieobecnosci')),
                ('data_koniec', models.DateField(verbose_name='data ostatniego dnia nieobecnosci')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nieobecność',
                'verbose_name_plural': 'nieobecności',
                'ordering': ['data_pub'],
            },
        ),
    ]
